---
title: "open_agenda"
author: "Paul Schneider"
date: "30.09.2019"
output: html_document
---
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

<br><br>

#### [EDIT AGENDA](https://docs.google.com/spreadsheets/d/1fAAtlsesJY_LpE1MCnS87oDqVebkaMLG4dLLoBAfRNA/edit?usp=sharing)

<br>
```{r message=FALSE, warning=FALSE, include=FALSE}
# load pkg
  # install.packages("gsheet")
  # install.packages("RColorBrewer")
  # install.packages("timevis")
  library(gsheet)
  library(RColorBrewer)
  library(timevis)

# read data from gsheet
  url <- 'https://docs.google.com/spreadsheets/d/1fAAtlsesJY_LpE1MCnS87oDqVebkaMLG4dLLoBAfRNA/edit?usp=sharing'
  myGanttTable <- gsheet2tbl(url)


# cust fun
  ColorizeGantt = function(gantttbl = myGanttTable){
    proj.colors = data.frame(group = unique(gantttbl$group),
                             style = brewer.pal(length(unique(gantttbl$group)), "Set1"))
    proj.colors = merge(gantttbl,proj.colors,by="group",sort = F)
    proj.colors$style = paste("background:",proj.colors$style)
    # proj.colors = paste(paste("'",proj.colors$col,"'", sep=""),sep="",collapse = ",")
    # proj.colors = paste("[",proj.colors,"]")
    return(proj.colors$style)
  }
  make_check_box = function(item,deadline="", checked = F){
      deadline = format(deadline,format="%d %b %Y")
    if(checked){
    cat('<tr>',
        '<td>',item,'</td>',
        '<td>',deadline,'<td>',
      '<td><input type="checkbox" name="" value="" checked></td>',
      '</tr>')      
  } 
    else {
    cat('<tr>',
        '<td>',item,'</td>',
        '<td>',deadline,'<td>',
      '<td><input type="checkbox" name="" value="" ></td>',
      '</tr>')      
    # cat('<input type="checkbox" name="" value="">',item,deadline,'<br>')      
  }
  }
  
  show_agenda = function(title="AGENDA",task = agenda_data$content,deadlines,status){
  cat("<details> <summary><strong>",title,"</strong></summary><br><p>")
    
    cat('<table style="width:50%">
  <tr>
    <th align="left">Task</th> 
    <th align="left">Deadline</th>
    <th align="left">Status</th>
  </tr>')
    
    for(i in 1:length(task)){
      make_check_box(task[i],deadline = deadlines[i],checked = status[i])  
    }

  cat("</table></p></pre></details>")
}
  
```


```{r echo=FALSE, message=FALSE, warning=FALSE,results="asis"}
# to do list
agenda_data =  myGanttTable[,c("content","end","completed")]
agenda_data = agenda_data[!is.na(agenda_data$content),]

# completed?
agenda_data$completed[is.na(agenda_data$completed)] = F
donevar = c("yes","Yes","y","Y","x","X","done","Done")
agenda_data$completed[agenda_data$completed %in% donevar] = T

# sort
agenda_data = agenda_data[order(agenda_data$end,decreasing = F),]
agenda_data_comp = agenda_data[agenda_data$completed ==T,]
agenda_data_noncomp = agenda_data[agenda_data$completed ==F,]

show_agenda(title = "OPEN TASKS",
            task = agenda_data_noncomp$content,
            deadlines = agenda_data_noncomp$end,
            status = agenda_data_noncomp$completed)
cat("<br>")
show_agenda(title = "Show all tasks",
            task = agenda_data$content,
            deadlines = agenda_data$end,
            status = agenda_data$completed)
```


<br>

****
#### __GANTT CHART__


```{r setup, include=FALSE}
# create some labels etc
myGanttTable = myGanttTable[!is.na(myGanttTable$group),] 
myGanttTable$subgroup = myGanttTable$start
deadline = format(myGanttTable$end ,format ="%d.%m.")
myGanttTable$title = paste(myGanttTable$content,"Deadline:",deadline)
myGanttTable$style =  ColorizeGantt(myGanttTable)
myGanttTable_point = myGanttTable
myGanttTable$type = "range"
myGanttTable_point$type = "box"
myGanttTable_point$start = myGanttTable_point$end
myGanttTable_point$content=""
myGanttTable_point$end = NA
myGanttTable = rbind(myGanttTable,myGanttTable_point)

# create group ID and order
myGanttTable = myGanttTable[order(myGanttTable$start,decreasing = T),]
myGanttTable_group = data.frame(id = as.numeric(as.factor(myGanttTable$group)),content = myGanttTable$group)
myGanttTable$group = as.numeric(as.factor(myGanttTable$group)) 
myGanttTable_group$subgroupOrder = "content"
myGanttTable_group = myGanttTable_group[!duplicated(myGanttTable_group$id),]

# config
config <- list(
  editable = F,
  align = "center",
  orientation = "center",
  snap = NULL,
  stack = F,
  selectable	=T,
  margin = list(item = 10, axis = 50))

# plot
ganttplot = timevis(myGanttTable, groups = myGanttTable_group,width = "100%", options = config,fit=T)
# htmlwidgets::saveWidget(ganttplot,file="ps_gantt.html",selfcontained = F)
# browseURL("ps_gantt.html")
```



```{r echo=FALSE}
ganttplot
```





